# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_theme:
        - 'bootstrap_3_horizontal_layout.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver:   sequel
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

parameters:
    app.locales: en|es
    locale: en
    database_host: 10.255.255.255
    database_port: 9999
    database_name: testdbname
    database_user: dbname
    database_password: password

